/*
 * @author Joshua Henderson
 */
public class Application {

	public static void main(String[] args) {
		Building data1 = new Building();
		data1.setProjectName("House");
		System.out.println(data1.getProjectName());
		data1.setCompleteAddress("123 main street");
		System.out.println(data1.getCompleteAddress());
		data1.setTotalSquareFeet(23445);
		System.out.println(data1.getTotalSquareFeet());
		data1.setOccupancyGroup("Assembly");
		System.out.println(data1.getOccupancyGroup());
		data1.setSubgroup("Assembly");
		System.out.println(data1.getSubgroup());
		System.out.println(data1.displayData());
		System.out.println(data1.toString());
		data1.draw();
		Business data2 = new Business();
		data2.setProjectName("MCM");
		System.out.println(data2.getProjectName());
		data2.setCompleteAddress("123 main street");
		System.out.println(data2.getCompleteAddress());
		data2.setTotalSquareFeet(23445);
		System.out.println(data2.getTotalSquareFeet());
		data2.setOccupancyGroup("Business");
		System.out.println(data2.getOccupancyGroup());
		data2.setSubgroup("Business");
		System.out.println(data2.getSubgroup());
		data2.setNumRentableUnits(3);
		System.out.println(data2.getNumRentableUnits());
		System.out.println(data2.displayData());
		System.out.println(data2.toString());
		data2.drawBusiness();
		Mall data3 = new Mall();
		data3.setProjectName("MCM");
		System.out.println(data3.getProjectName());
		data3.setCompleteAddress("123 main street");
		System.out.println(data3.getCompleteAddress());
		data3.setTotalSquareFeet(23445);
		System.out.println(data3.getTotalSquareFeet());
		data3.setOccupancyGroup("Business");
		System.out.println(data3.getOccupancyGroup());
		data3.setSubgroup("Business");
		System.out.println(data3.getSubgroup());
		data3.setNumRentableUnits(3);
		System.out.println(data3.getNumRentableUnits());
		data3.setNumRentedUnits(23445);
		System.out.println(data3.getNumRentedUnits());
		data3.setMedianUnitSize(23445);
		System.out.println(data3.getMedianUnitSize());
		data3.setNumParkingSpaces(23445);
		System.out.println(data3.getNumParkingSpaces());
		System.out.println(data3.displayDataMall());
		System.out.println(data3.toString());
		data3.drawMall();
		Residential data4 = new Residential();
		data4.setProjectName("House");
		System.out.println(data4.getProjectName());
		data4.setCompleteAddress("123 main street");
		System.out.println(data4.getCompleteAddress());
		data4.setTotalSquareFeet(23445);
		System.out.println(data4.getTotalSquareFeet());
		data4.setOccupancyGroup("Residential");
		System.out.println(data4.getOccupancyGroup());
		data4.setSubgroup("R-1");
		System.out.println(data4.getSubgroup());
		data4.setNumBedrooms(0);
		System.out.println(data4.getNumBedrooms());
		data4.setNumBathrooms(0);
		System.out.println(data4.getNumBathrooms());
		data4.setLaundryRoom(true);
		System.out.println(data4.isLaundryRoom());
		System.out.println(data4.displayDataResidential());
		System.out.println(data4.toString());
		data4.drawResidential();
		Apartment data5 = new Apartment();
		data5.setProjectName("House");
		System.out.println(data5.getProjectName());
		data5.setCompleteAddress("123 main street");
		System.out.println(data5.getCompleteAddress());
		data5.setTotalSquareFeet(23445);
		System.out.println(data5.getTotalSquareFeet());
		data5.setOccupancyGroup("Residential");
		System.out.println(data5.getOccupancyGroup());
		data5.setSubgroup("R-1");
		System.out.println(data5.getSubgroup());
		data5.setNumBedrooms(0);
		System.out.println(data5.getNumBedrooms());
		data5.setNumBathrooms(0);
		System.out.println(data5.getNumBathrooms());
		data5.setLaundryRoom(true);
		System.out.println(data5.isLaundryRoom());
		data5.setNumRentableUnits(0);
		System.out.println(data5.getNumRentableUnits());
		data5.setAvgUnitSize(0);
		System.out.println(data5.getAvgUnitSize());
		data5.setParkingAvailable(false);
		System.out.println(data5.isParkingAvailable());
		System.out.println(data5.displayDataApartment());
		System.out.println(data5.toString());
		data5.drawApartment();
		SingleFamilyHome data6 = new SingleFamilyHome();
		data6.setProjectName("House");
		System.out.println(data6.getProjectName());
		data6.setCompleteAddress("123 main street");
		System.out.println(data6.getCompleteAddress());
		data6.setTotalSquareFeet(23445);
		System.out.println(data6.getTotalSquareFeet());
		data6.setOccupancyGroup("Residential");
		System.out.println(data6.getOccupancyGroup());
		data6.setSubgroup("R-1");
		System.out.println(data6.getSubgroup());
		data6.setNumBedrooms(0);
		System.out.println(data6.getNumBedrooms());
		data6.setNumBathrooms(0);
		System.out.println(data6.getNumBathrooms());
		data6.setLaundryRoom(true);
		System.out.println(data6.isLaundryRoom());
		data6.setGarage(false);
		System.out.println(data6.isGarage());
		System.out.println(data6.displayDataSingleFamilyHome());
		System.out.println(data6.toString());
		data6.drawSingleFamilyHome();

	}

}
